language: php

php:
  - '7.0'

before_script:
  - composer self-update
  - composer install --no-interaction

notifications:
  email:
    recipients:
      - tcwa.service@gmail.com
    on_success: change
    on_failure: always

script: phpunit -c phpunit.xml --coverage-text
