language: php

php:
  - '7.0'
  - '7.1'

install:
  - composer install --prefer-dist --no-dev --optimize-autoloader --quiet

notifications:
  email:
    recipients:
      - tcwa.service@gmail.com
    on_success: change
    on_failure: always

script: phpunit -c phpunit.xml --coverage-text
